library(tibble)
library(cvms)
library(readxl)
library(tidyverse)
library(vcd)
library(caret)
library(reshape)

result <- read_excel("C:/Users/mjdee/Desktop/JI-2020/JI-医师验证/结果.xlsx")
result<-result[,1:8]
real<-read.csv("C:/Users/mjdee/Desktop/JI-2020/JI-医师验证/predicted.csv")
real<-select(real,id,真实死活)
result<-merge(result,real,by="id")
mydata<-select(result,group,id,pre_result,真实死活)
jresult<-filter(mydata,group=="control_J" |group=="experi_J")
md<-melt(jresult,id=c("id","group","真实死活"))
jresult_table<-cast(md,id+真实死活~group)
jresult_table$control_J<-factor(jresult_table$control_J)
jresult_table$experi_J<-factor(jresult_table$experi_J)
jresult_table$真实死活<-factor(jresult_table$真实死活)
example1 <- confusionMatrix(data=jresult_table$control_J, reference = jresult_table$真实死活)
example2 <- confusionMatrix(data=jresult_table$experi_J, reference = jresult_table$真实死活)
